# Generated by Django 3.2 on 2023-05-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_service_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='AdminApp.category'),
            preserve_default=False,
        ),
    ]
